# Nut Butter Store Sales

In [3]:
import numpy as np
import pandas as pd

np.random.seed(0)
# number of jars sold
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [4]:
# create weekly_sales dataframe
weekly_sales = pd.DataFrame(sales_amounts,
                            index=['Mo', 'Tue', 'Wed', 'Thu', 'Fri'],
                            columns=['Almond butter', 'Peanut butter', 'Cashew butter'])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mo              12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [5]:
# create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [8]:
prices.shape

(3,)

In [7]:
# create butter_prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=['Prices'],
                             columns=['Almond butter', 'Peanut butter', 'Cashew butter'])
butter_prices

Almond butter  Peanut butter  Cashew butter
Prices             10              8             12

In [27]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [20]:
sales_amounts.T

array([[12,  3,  9,  4,  1],
       [15,  3, 19,  6,  6],
       [ 0,  7, 18, 12,  7]])

In [26]:
prices

array([10,  8, 12])

In [23]:
prices.shape, sales_amounts.T.shape

((3,), (3, 5))

In [36]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [28]:
# create daily_sales
butter_prices

Almond butter  Peanut butter  Cashew butter
Prices             10              8             12

In [29]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mo              12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [30]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [31]:
butter_prices.shape, weekly_sales.T.shape

((1, 3), (3, 5))

In [35]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mo  Tue  Wed  Thu  Fri
Prices  240  138  458  232  142

In [37]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mo              12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [39]:
weekly_sales['Total ($)'] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mo              12             15              0        240
Tue              3              3              7        138
Wed              9             19             18        458
Thu              4              6             12        232
Fri              1              6              7        142