# ztm61-datatypes and attributes

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim #number of dimension

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size #number of elements

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# create a dataframe from a numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

## ztm62-create numpy arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
sample_array.ndim

1

In [19]:
type(sample_array)

numpy.ndarray

In [20]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10, 3)
range_array

array([0, 3, 6, 9])

In [25]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 2, 9, 9, 7],
       [6, 2, 0, 9, 5],
       [1, 0, 3, 1, 2]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array2 = np.random.random((5, 4))
random_array2

array([[0.90941911, 0.21263136, 0.8238468 , 0.17901634],
       [0.91106988, 0.98284214, 0.71075407, 0.57205094],
       [0.76941799, 0.0492235 , 0.44001929, 0.64737034],
       [0.62310606, 0.35028396, 0.54601152, 0.73738864],
       [0.78228931, 0.58966185, 0.62184885, 0.70534301]])

In [29]:
random_array2.shape

(5, 4)

In [30]:
random_array3 = np.random.rand(3, 5)
random_array3

array([[0.70230235, 0.21265281, 0.99803247, 0.42636364, 0.08753905],
       [0.19637667, 0.86033834, 0.97457036, 0.26836745, 0.99967684],
       [0.81068858, 0.109394  , 0.04942723, 0.52209639, 0.35389168]])

In [31]:
np.random.rand(3, 5, 2)

array([[[0.50787598, 0.85199397],
        [0.30521498, 0.69288305],
        [0.55849608, 0.00668659],
        [0.07866822, 0.71706692],
        [0.00996132, 0.91051014]],

       [[0.0769671 , 0.56141413],
        [0.05429451, 0.75741752],
        [0.35926896, 0.01325814],
        [0.37587738, 0.9550718 ],
        [0.02725924, 0.54069537]],

       [[0.98101936, 0.45205487],
        [0.17444152, 0.88666389],
        [0.73222453, 0.75872987],
        [0.57674941, 0.3989376 ],
        [0.79769297, 0.08266756]]])

In [32]:
np.random.rand(3, 5, 2, 4)

array([[[[0.61746273, 0.72578537, 0.57989792, 0.26222992],
         [0.074828  , 0.96886514, 0.5179773 , 0.58518843]],

        [[0.09837912, 0.62588231, 0.67012822, 0.70745327],
         [0.04524613, 0.02040722, 0.71180305, 0.87646239]],

        [[0.94117636, 0.06578062, 0.46944205, 0.88504808],
         [0.39501017, 0.28673013, 0.44332006, 0.7263344 ]],

        [[0.40473891, 0.25744903, 0.28858033, 0.5688711 ],
         [0.81318993, 0.93687111, 0.05527848, 0.10034379]],

        [[0.6661847 , 0.92472694, 0.1154087 , 0.1862105 ],
         [0.52719481, 0.67478847, 0.99789643, 0.72725481]]],


       [[[0.67082717, 0.57998744, 0.7950907 , 0.06853481],
         [0.32605395, 0.22984094, 0.41546178, 0.7841392 ]],

        [[0.54780699, 0.88989352, 0.13808296, 0.91017677],
         [0.82944021, 0.10651911, 0.43006986, 0.25768225]],

        [[0.87448318, 0.60647544, 0.25154338, 0.38152136],
         [0.97179054, 0.86091992, 0.66599627, 0.32971057]],

        [[0.11263073, 0.31158157, 0.76

## ztm63-random seed

In [40]:
np.random.seed(seed=99999)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [34]:
random_array4.shape

(5, 3)

In [42]:
np.random.seed(7)
random_array5 = np.random.random((5, 3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## ztm64-viewing arrays and matrices

In [44]:
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [43]:
np.unique(random_array4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [45]:
a1

array([1, 2, 3])

In [46]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [47]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
a1[0]

1

In [49]:
a2[0]

array([1. , 2. , 3.3])

In [50]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [52]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [53]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [60]:
a4[:2, :3, :1 , :5]

array([[[[3, 5, 8, 8, 7]],

        [[1, 0, 0, 6, 7]],

        [[4, 3, 1, 9, 5]]],


       [[[3, 0, 4, 8, 6]],

        [[9, 9, 0, 6, 2]],

        [[7, 5, 4, 9, 6]]]])

In [62]:
a4[:, :, :, :3]

array([[[[3, 5, 8],
         [5, 0, 0],
         [9, 6, 4],
         [3, 3, 8]],

        [[1, 0, 0],
         [7, 9, 3],
         [7, 7, 0],
         [3, 1, 3]],

        [[4, 3, 1],
         [9, 1, 2],
         [2, 5, 7],
         [9, 9, 3]]],


       [[[3, 0, 4],
         [7, 2, 7],
         [6, 6, 5],
         [7, 1, 5]],

        [[9, 9, 0],
         [6, 8, 2],
         [6, 1, 5],
         [9, 8, 6]],

        [[7, 5, 4],
         [8, 1, 5],
         [3, 7, 7],
         [7, 5, 9]]]])